### PR TITLE
Feature/contributing readme guidelines

### PR DESCRIPTION
**Pull request by a-chow-cse**
Template for README.md for both main repository and sub project repository.

### CODE REVIEW

**Comment by thompsonmj** [comment]
This is a great README template that spurs some thought.

It's generally a good idea to scope a repository around a single product built to serve a specific purpose. In this case, the purpose is to provide AI explainability features useful in the domain areas investigated by researchers in the institute (or possibly more broadly eventually, but with this more narrow focus to begin with probably being helpful). 

It might make sense to rather refer to the 'subprojects' as features or modules and classify them as 'subproducts,' since their goal is likely to provide some valueable utility to enable insight and be used as a tool.

Organizing the repo structure should enable both good engineering and some room to do the messier research activities like experimenting, exploring, and investigating new ideas. But first, maybe we could draft a clear description of what the state of AI explainability at the Imageomics is, and what the vision is specifically regarding David's and Arpita's work.

**Comment by hlapp** [comment]
Some additional thoughts / comments:

- I would agree that in general it works best if a code repository is scoped for one project, not multiple ones. Code repositories are best thought of as implementations, not conceptual-level projects under which one or more "subprojects" may fall. If the desire is to track tasks across a number of conceptually related repositories, then this can actually be done through [organization-level project boards](https://github.com/orgs/Imageomics/projects), and does not necessitate having the codebases together in a single code repository.
- Having said that, it is possible in Git to later separate code from one repository into another repository, all the while accurately preserving its entire commit (and therefore contribution) history. Therefore, if the "subprojects" here are expected to use (share) some of the same code, it's OK to start with initially having everything in a single repository. Note though that separating out code later is most straightforward if it's all under a subdirectory, so if "subprojects" and shared code can each be organized in separate subdirectories, that best lays the ground for future separation if initial separation seems hindering progress.
- I agree that front READMEs aren't well suited to include document templates. (Arguably, neither are READMEs in nested subdirectories.) It's most straightforward to convert a template into a document following the template if one can just copy a template document to the desired target document. That said, the README(s) can and should certainly _link_ to the template document(s).
- In the realm of templates for contributing certain types documents, it may also be worth looking at whether and how [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) or [pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) could be leveraged. (@thompsonmj)

**Comment by a-chow-cse** [comment]
- I agree with @thompsonmj that this should be "submodules" as the modules under repository should serve almost equal purpose. I will change "subprojects" to "submodules".
- I agree with @hlapp that we can divide the submodules into different directory if it's needed in future.
- I will delete the attached template submodule README from main README.md file. As, for now, David and I both will have the template to put the instructions in. Maybe @thompsonmj and I can look into pull request template for this purpose.

**Comment by thompsonmj** [comment]
So taking the idea Hilmar mentioned that "code repositories are best thought of as implementations," we might aspire to having an I-XAI (Imageomics-eXplainable AI, or something like that) library representing the pro**duct** that results from the pro**jects** of David's and Arpita's research, which would be accessible through something like `pip install i-xai` and/or `conda install -c conda-forge i-xai`. 

To handle the idea of minimizing the redundant implementation shared methods between David and Arpita, the work that David had started with the [ml_toolbox](https://github.com/Imageomics/ml_toolbox) repo could be resurrected and made into another actively developed library that could be imported to `i-xai` as a dependency. This could first be extended with generalizable forms of some of the current files under the current `ai-explainability` repo like `data_tools.py`, `utils.py`, etc. 

Then the `i-xai` package would have various Imageomics domain-specific methods like a tuned Grad-CAM, point similarity tools, and so on that could be used by people interested in explaining biological classifiers, trait ID, etc. This would make writing a clear and user/audience-focused README with information about installation, dependencies, usage examples, links to contributing guidelines and license info, etc quite tractable, as well as documentation.

If we frame these thoughts as longer-term milestones on a roadmap, we might benefit from having some slightly 'messier' research-based repositories that can be managed independently by David and Arpita for the sake of lowering the barrier to getting progress. Then, work can be migrated to these library repositories as it matures.

Any thoughts on that approach?

**Comment by DavidCarlyn** [comment]
I like the idea of making the [ml_toolbox](https://github.com/Imageomics/ml_toolbox) repo a dependency for this repository. That would help clean up this repository's scope a bit more. If this repository is to be more finished products, then are we splitting out @a-chow-cse and my research code into separate repositories? I may still be confused on this part @thompsonmj

**Comment by thompsonmj** [comment]
To make that decision, it would be helpful to see an abstract of @DavidCarlyn's and @a-chow-cse's research. 

Like Hilmar has mentioned, keeping enough space for each of you to work comfortably by having project-scoped repositories has merits, and refactoring research-grade code into the production ml-toolbox and i-xai (or whatever _this_ repository becomes) could take place along the way. There will undoubtedly be plenty of idiosyncratic scripts that will be needed to manage things for each of your individual research products like presentations, figures, and all kinds of other research artifacts, and I think that is what Hilmar is thinking of when he suggests repositories scoped around research projects either now or later. 

A distinct README for each research project could be advantageous to center around the research questions the projects are addressing, and a research project repo README would likely look quite different from a library README focused around the utility offered to the user and the mechanics of how to get that utility.

**Comment by thompsonmj** [comment]
Closing this since Arpita will keep her project work separate, and we'll make a README for each project repo.

**Pull request closed without merging**
